name: barcode_scanner_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  barcode_scan2: ^4.3.0
  # cloud_firestore: ^4.13.6
  # firebase_core: ^2.24.2
  flutter:
    sdk: flutter 
  fluttertoast: ^8.2.4
  http: ^1.1.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
