// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0kOHnKPnSibo-SKEayPeTSRF2FDYtq58',
    appId: '1:949777463029:web:aca145e0f0933edfca37bc',
    messagingSenderId: '949777463029',
    projectId: 'barcode-scanner-app-86156',
    authDomain: 'barcode-scanner-app-86156.firebaseapp.com',
    storageBucket: 'barcode-scanner-app-86156.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT--HnrcdcQH5LjHo0AoA76eZ0ck26QGk',
    appId: '1:949777463029:android:f64c97cff66f6119ca37bc',
    messagingSenderId: '949777463029',
    projectId: 'barcode-scanner-app-86156',
    storageBucket: 'barcode-scanner-app-86156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRL5p_iNI6BUc4hyuVtxo94uKPMHywj8',
    appId: '1:949777463029:ios:359316e43c25607fca37bc',
    messagingSenderId: '949777463029',
    projectId: 'barcode-scanner-app-86156',
    storageBucket: 'barcode-scanner-app-86156.appspot.com',
    iosBundleId: 'com.example.barcodeScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRL5p_iNI6BUc4hyuVtxo94uKPMHywj8',
    appId: '1:949777463029:ios:a6b5b739bb71068bca37bc',
    messagingSenderId: '949777463029',
    projectId: 'barcode-scanner-app-86156',
    storageBucket: 'barcode-scanner-app-86156.appspot.com',
    iosBundleId: 'com.example.barcodeScannerApp.RunnerTests',
  );
}
